name: Check markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@master